"""Initial schema — all 29 tables.

Revision ID: 001_initial
Revises:
Create Date: 2026-04-15

Uses Base.metadata.create_all so the schema stays a 1:1 projection of the
SQLAlchemy models. Subsequent migrations should be autogenerated with
`alembic revision --autogenerate` and committed as normal ops.
"""
from typing import Sequence, Union

from alembic import op

from app.models import Base

revision: str = "001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    # pgcrypto provides gen_random_uuid() used as column default
    bind.exec_driver_sql('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
